### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/class_2338

### ISSUE THREAD

**Issue by GUAZIGEGE1337** [jar-analyzer/jar-obfuscator#25]
Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/class_2338
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:874)
        at me.n1ar4.jar.obfuscator.loader.CustomClassLoader.findClass(CustomClassLoader.java:14)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at me.n1ar4.jar.obfuscator.loader.CustomClassWriter.getCommonSuperClass(CustomClassWriter.java:29)
        at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1264)
        at org.objectweb.asm.Frame.merge(Frame.java:1311)
        at org.objectweb.asm.Frame.merge(Frame.java:1208)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1612)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
        at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:786)
        at me.n1ar4.jar.obfuscator.asm.JunkCodeChanger$JunkChangerMethodAdapter.visitMaxs(JunkCodeChanger.java:372)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2664)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1512)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:745)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
        at me.n1ar4.jar.obfuscator.transform.JunkCodeTransformer.transform(JunkCodeTransformer.java:40)
        at me.n1ar4.jar.obfuscator.core.Runner.run(Runner.java:362)
        at me.n1ar4.jar.obfuscator.Main.main(Main.java:72)
        
        麻烦问一下这种是因为什么，改怎么解决，求大佬解答

**Comment by 4ra1n** [comment]
因为花质量模块是需要尝试 loadClass 的，简单来说关闭 junkCode 即可解决，彻底的办法我再研究看看

**Comment by 4ra1n** [comment]
0.2.0
