### ISSUE TITLE
师傅，这个报错具体是什么原因呢

### ISSUE THREAD

**Issue by KANAZAWA1** [jar-analyzer/jar-obfuscator#3]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /混淆/code-encryptor-temp/libencryptor.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1823)
	at java.lang.Runtime.load0(Runtime.java:782)
	at java.lang.System.load(System.java:1098)
	at me.n1ar4.jar.obfuscator.utils.JNIUtil.loadLib(JNIUtil.java:81)
	at me.n1ar4.jar.obfuscator.jvmti.PatchHelper.patchJar(PatchHelper.java:38)
	at me.n1ar4.jar.obfuscator.jvmti.PatchCommand.execute(PatchCommand.java:71)
	at me.n1ar4.jar.obfuscator.core.Runner.run(Runner.java:328)
	at me.n1ar4.jar.obfuscator.Main.main(Main.java:66)

**Comment by 4ra1n** [comment]
你是否开启了 `enableSuperObfuscate` 选项

提供下年底 JDK 版本

是 MAC 还是 LINUX

**Comment by 4ra1n** [comment]
OK，可以测试下有没有其他的 BUG

那个选项我仅测试过 WINDOWS 和 LINUX

MAC 上可能有问题
